name: kamera_mantap

description: "A new Flutter project using camera."

publish_to: 'none' # Hanya untuk proyek lokal, hapus jika ingin dipublikasikan

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0







dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
